// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc746.Robot7462018;

import edu.wpi.cscore.CvSink;
import edu.wpi.cscore.CvSource;
import edu.wpi.cscore.UsbCamera;
import edu.wpi.first.wpilibj.CameraServer;
import edu.wpi.first.wpilibj.TimedRobot;
import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.command.Scheduler;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj.networktables.NetworkTable;
import edu.wpi.first.wpilibj.smartdashboard.SendableChooser;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

import org.opencv.core.Mat;
import org.usfirst.frc746.Robot7462018.commands.*;
import org.usfirst.frc746.Robot7462018.subsystems.*;

/**
 * The VM is configured to automatically run this class, and to call the
 * functions corresponding to each mode, as described in the TimedRobot
 * documentation. If you change the name of this class or the package after
 * creating this project, you must also update the build.properties file in 
 * the project.
 */
public class Robot extends TimedRobot {

    Command autonomousCommand;
    //SendableChooser<String> chooser = new SendableChooser<>();
    SendableChooser<Command> chooser = new SendableChooser<>();
    final String autonomousTest = "Auto Test";
    final String AutoLeftBlue = "Auto LBlue";

    public static OI oi;
    public static DriveTrain driveTrain;
    public static Arm arm;
    public static Intake intake;
    private UsbCamera camera0;
	private UsbCamera camera1;

    

    /**
     * This function is run when the robot is first started up and should be
     * used for any initialization code.
     */
    @Override
    public void robotInit() {
        RobotMap.init();

        driveTrain = new DriveTrain();
        arm = new Arm();
        intake = new Intake();

        // OI must be constructed after subsystems. If the OI creates Commands
        //(which it very likely will), subsystems are not guaranteed to be
        // constructed yet. Thus, their requires() statements may grab null
        // pointers. Bad news. Don't move it.
        oi = new OI();

        // Add commands to Autonomous Sendable Chooser
      

        //chooser.addObject("AutoLeftBlue",  AutoLeftBlue);
        //chooser.addObject("autonomousTest", autonomousTest);
        //chooser.addDefault("Autonomous Command", new AutonomousCommand());
        chooser = new SendableChooser<Command>();
        chooser.addObject("Auto Left Blue", new AutoLeftBlue());
        chooser.addObject("Autonomous Test", new autonomousTest());
        SmartDashboard.putData("Auto mode", chooser);
        
        Thread t = new Thread(() -> {
			boolean allowCam1 = false;
			UsbCamera Cam1 = CameraServer.getInstance().startAutomaticCapture();
			Cam1.setResolution(320, 240);
			Cam1.setFPS(20);
			UsbCamera Cam2 = CameraServer.getInstance().startAutomaticCapture();
			Cam2.setResolution(320, 240);
			Cam2.setFPS(20);
			// MjpegServer server = new MjpegServer("Output to dashboard",
			// 5800);

			CvSink cvSink1 = CameraServer.getInstance().getVideo(Cam1);
			CvSink cvSink2 = CameraServer.getInstance().getVideo(Cam2);
			CvSource outputStream = CameraServer.getInstance().putVideo("Switcher", 320, 240);
			Mat image = new Mat();
			while (!Thread.interrupted()) {

				if (oi.getDriver1().getRawButton(9)) {
					allowCam1 = !allowCam1;
				}
				if (allowCam1) {

					cvSink2.setEnabled(false);
					cvSink1.setEnabled(true);
					cvSink1.grabFrame(image);
				} else {
					cvSink1.setEnabled(false);
					cvSink2.setEnabled(true);
					cvSink2.grabFrame(image);

				}
				outputStream.putFrame(image);

			}

		});
		t.start();
		
		/*
		camera0 = CameraServer.getInstance().startAutomaticCapture();
		camera1 = CameraServer.getInstance().startAutomaticCapture();
		 */
		
    }

    /**
     * This function is called when the disabled button is hit.
     * You can use it to reset subsystems before shutting down.
     */
    @Override
    public void disabledInit(){
    	Robot.driveTrain.stop();
    	Robot.arm.stop();
    	Robot.intake.stop();

    }

    @Override
    public void disabledPeriodic() {
        Scheduler.getInstance().run();
    }

    @Override
    public void autonomousInit() {
       
    	/*
    	String autoSelected = chooser.getSelected();
        System.out.println("Auto selected: " + autoSelected);
		switch (autoSelected) {
		case autonomousTest:
			autonomousCommand = new autonomousTest();
			break;
		case AutoLeftBlue:
			autonomousCommand = new AutoLeftBlue();
			break;
		}
		*/
    	autonomousCommand = (Command) chooser.getSelected();    
        if (autonomousCommand != null) autonomousCommand.start();
    }

    /**
     * This function is called periodically during autonomous
     */
    @Override
    public void autonomousPeriodic() {
        Scheduler.getInstance().run();
    }

    @Override
    public void teleopInit() {
        // This makes sure that the autonomous stops running when
        // teleop starts running. If you want the autonomous to
        // continue until interrupted by another command, remove
        // this line or comment it out.
        if (autonomousCommand != null) autonomousCommand.cancel();
    }

    /**
     * This function is called periodically during operator control
     */
    @Override
    public void teleopPeriodic() {   	
        Scheduler.getInstance().run();
        
        
        /*
        if (oi.getDriver1().getRawButton(9)) {
			NetworkTable.getTable("").putString("CameraSelection", camera0.getName());
		} else if (oi.getDriver1().getRawButton(1)) {
			NetworkTable.getTable("").putString("CameraSelection", camera1.getName());
		}
		*/
	}
	
    }

